### ISSUE TITLE
PubSub not writing to channel

### ISSUE THREAD

**Issue by tvarwig** [mediocregopher/radix.v3#2]
The Example code for PubSub in GoDoc does not write to a channel when there are a separate publisher and subscriber. The GoDoc example runs correctly when on one go program.  My Code is below.

publisher.go
```
package main

import (
	"github.com/mediocregopher/radix.v3"
	"time"
	"github.com/satori/go.uuid"
	"log"
)

func main(){
	stub, stubCh := radix.PubSubStub("tcp", "localhost:6379", func([]string) interface{} {
		return nil
	})

	pstub := radix.PubSub(stub)
	if pstub.Ping() != nil {
		log.Fatal(pstub.Ping())
	}

	for {
		stubCh <- radix.PubSubMessage{
			Channel: "foo",
			Message: []byte(uuid.NewV4().String()),
		}
		time.Sleep(1 * time.Second)
	}
}
```

subscriber.go
```
package main

import (
	"github.com/mediocregopher/radix.v3"
	"log"
)

func main(){
	stub, _ := radix.PubSubStub("tcp", "localhost:6379", func([]string) interface{} {
		return nil
	})

	// Use PubSub to wrap the stub like we would for a normal redis connection
	pstub := radix.PubSub(stub)

	// Subscribe msgCh to "foo"
	msgCh := make(chan radix.PubSubMessage)
	if err := pstub.Subscribe(msgCh, "foo"); err != nil {
		log.Fatal(err)
	}

	// now msgCh is subscribed the publishes being made by the go-routine above
	// will start being written to it
	for m := range msgCh {
		log.Printf("%v", string(m.Message))
	}
}
```

**Comment by mediocregopher** [comment]
Hey @tvarwig, just to be clear, are you running these as two separate binaries? Cause if so that's the problem.

A stub is essentially a placeholder for an external entity that gets used in things like tests because it can be easier than using the actual entity. So in this case PubSubStub is a placeholder for a pubsub enabled redis connection, not a real one.

To make a real pubsub connection you should do:

```go
conn, err := radix.Dial("tcp", "localhost:6379")
if err != nil {
    panic(err)
}

ps := radix.PubSub(conn)
// rest of your subscription code stays the same
```

and to publish to it you can call the PUBLISH redis command normally

```go
conn, err := radix.Dial("tcp", "localhost:6379")
if err != nil {
    panic(err)
}

for {
    err := conn.Do(radix.Cmd(nil, "PUBLISH", "foo", uuid.NewV4().String())
    if err != nil {
        panic(err)
    }
    time.Sleep(1 * time.Second)
}
```

This is more a fault of the documentation not being clear than anything. I'll update the Stub and PubSubStub docs to make it clearer that they're not real redis connections, as well as add an example onto PubSub to show it being used with a real connection.

Thanks for trying out v3, definitely let me know if you have any other questions or issues :)

**Comment by mediocregopher** [comment]
Going to go ahead and assume this is resolved, feel free to reopen it if that's not the case
