### ISSUE TITLE
Getting issue while using Radix V3

### ISSUE THREAD

**Issue by DineshGuptaa** [mediocregopher/radix.v3#4]
Hi,
I didn't find the migration guide from V2 to V3. I face a lot issue while trying to sample.
I found working sample and trying to convert it on V3 but didn't get success

http://www.alexedwards.net/blog/working-with-redis

db.Do(radix.FlatCmd(exists, "EXISTS", "album:2"))
can't unmarshal into int

I tried many option but....

If you can guide me how we can utilize the Radix v3 for provide me samples it will very helpful.

Thanks,
Dinesh Gupta

**Comment by mediocregopher** [comment]
Hi @DineshGuptaa, thanks for trying out V3. There is not currently a migration guide for V2->V3, although that's definitely something I should work on.

For your example, what is the type of the `exists` variable? It ought to be a pointer, similar to how unmarshaling for the json package works. Under the "Commands" section of the package doc there's a similar example for unmarshaling into an int which looks like this:

```
var barI int
err := client.Do(radix.Cmd(&barI, "INCR", "bar"))
```

(Note for your example, since all arguments are strings, you could use `Cmd` or `FlatCmd`, either will work)

**Comment by DineshGuptaa** [comment]
Hi Mediocregopher ,
Thanks for quick reply.

I tried both of the options
var exist int
err := db.Do(radix.Cmd(&exist, "EXISTS", "album:2"))
 2017/11/30 12:00:18 ERR unknown command 'album:2'
When printing the exist value show 1 which is correct. But listed command gives result but showing me error. Why?

Regards,
Dinesh Gupta

**Comment by mediocregopher** [comment]
Would you mind posting a full test case for what you're seeing? I did the following and it appears to work as expected for me:

```go
package main

import (
	"fmt"

	radix "github.com/mediocregopher/radix.v3"
)

func main() {
	db, err := radix.NewPool("tcp", "127.0.0.1:6379", 1, nil)
	if err != nil {
		panic(err)
	}

	var exist int
	err = db.Do(radix.Cmd(&exist, "EXISTS", "album:2"))
	fmt.Println(exist, err)
}
```

**Comment by DineshGuptaa** [comment]
Thanks. Will try as you suggested
